export const apiConsoleHtml = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>TenderBase API Console</title>
<style>
:root{font-family:Inter,Segoe UI,system-ui,sans-serif;color:#172033;background:#f4f7fb;line-height:1.45}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0}.hero{background:linear-gradient(135deg,#07101f,#10243d 62%,#0b6b49);color:#fff;padding:26px 5%}.hero-inner{max-width:1240px;margin:auto}.hero h1{margin:0 0 6px;font-size:30px}.hero p{margin:0;color:#c9d7e8}.wrap{max-width:1240px;margin:auto;padding:20px}.layout{display:grid;grid-template-columns:210px minmax(0,1fr);gap:18px;align-items:start}@media(max-width:850px){.layout{grid-template-columns:1fr}}.nav{position:sticky;top:12px}.nav strong{display:block;margin-bottom:8px}.nav a{display:block;padding:9px 10px;border-radius:8px;color:#52627a;text-decoration:none;font-size:13px;font-weight:800}.nav a:hover{background:#e9eff7;color:#0f172a}.card{background:#fff;border:1px solid #dbe3ee;border-radius:15px;padding:18px;margin-bottom:15px;box-shadow:0 7px 22px rgba(15,23,42,.045)}.card h2{margin:0 0 5px;font-size:19px}.muted{color:#697990;font-size:13px}.section-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:7px}.section-head span{font-size:11px;font-weight:800;color:#75849a;text-transform:uppercase;letter-spacing:.06em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:11px}@media(max-width:650px){.grid{grid-template-columns:1fr}}.field{display:grid;gap:5px;margin:8px 0}.field label{font-size:12px;font-weight:800;color:#40516a}input,select,textarea{width:100%;border:1px solid #cbd5e1;border-radius:8px;padding:9px 10px;font:inherit;background:#fff}textarea{min-height:160px;resize:vertical}button{border:0;border-radius:8px;padding:9px 13px;font:inherit;font-weight:800;cursor:pointer;background:#0f172a;color:#fff}button:hover{filter:brightness(1.08)}button.blue{background:#0ea5e9}button.green{background:#16a34a}.endpoint{border:1px solid #dfe6ef;border-radius:11px;padding:13px;margin:9px 0;background:#fbfcfe}.endpoint-title{display:flex;align-items:center;gap:7px}.endpoint-title strong{font-size:14px}.endpoint code{display:block;margin-top:3px;color:#46556c;font:12px ui-monospace,SFMono-Regular,Consolas,monospace}.badge{border-radius:6px;padding:3px 7px;color:#fff;font-size:10px;font-weight:900}.get{background:#0ea5e9}.post{background:#16a34a}.admin{border-left:4px solid #0f172a}.links{display:flex;gap:14px;flex-wrap:wrap;margin-top:8px}.links a{color:#087f73;text-decoration:none;font-weight:800;font-size:13px}.notice{padding:10px 12px;border-radius:9px;background:#fff7ed;border:1px solid #fed7aa;color:#9a3412;font-size:12px;margin-top:11px}.notice.ok{background:#ecfdf5;border-color:#bbf7d0;color:#166534}.status{padding:8px 10px;border-radius:8px;background:#eef3f9;color:#35455c;font-size:12px;margin-bottom:8px}.result{background:#0b1220;color:#d7e4f4;border-radius:10px;padding:13px;white-space:pre-wrap;overflow:auto;max-height:340px;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;margin:0}.response{position:sticky;bottom:10px}
</style>
</head>
<body>
<header class="hero"><div class="hero-inner"><h1>TenderBase API Console</h1><p>One workspace for search, municipal coverage, ingestion and tender management.</p></div></header>
<main class="wrap"><div class="layout">
<nav class="nav card"><strong>Workspace</strong><a href="#connection">Connection</a><a href="#public">Public API</a><a href="#admin">Admin API</a><a href="#response">Live response</a></nav>
<div>
<section id="connection" class="card"><div class="section-head"><h2>Connection</h2><span>Authentication</span></div><p class="muted">Public calls send <code>x-api-key</code>. Protected calls send <code>x-admin-key</code>. Keys are kept in this page only.</p><div class="grid"><div class="field"><label for="publicKey">Public API key</label><input id="publicKey" type="password" placeholder="Optional" /></div><div class="field"><label for="adminKey">Admin API key</label><input id="adminKey" type="password" placeholder="Render ADMIN_API_KEY" /></div></div><div class="links"><a href="/docs/json" target="_blank" rel="noreferrer">OpenAPI JSON</a><a href="/swagger" target="_blank" rel="noreferrer">Swagger reference</a></div><div id="authNotice" class="notice">Admin status will appear here after the first protected request.</div></section>
<section id="public" class="card"><div class="section-head"><h2>Public API</h2><span>Read-only</span></div><div id="publicEndpoints"></div></section>
<section id="admin" class="card admin"><div class="section-head"><h2>Admin API</h2><span>Protected</span></div><p class="muted">Municipality ingestion and manual tender controls.</p><div id="adminEndpoints"></div></section>
<section id="response" class="card response"><div class="section-head"><h2>Live response</h2><span id="responseMeta">Ready</span></div><div id="status" class="status">Ready — choose an operation.</div><pre id="result" class="result">No request has been made yet.</pre></section>
</div></div></main>
<script>
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
async function call(path,opts={},admin=false){const headers={'Accept':'application/json',...(opts.headers||{})};const key=admin?$('adminKey').value:$('publicKey').value;if(key)headers[admin?'x-admin-key':'x-api-key']=key;$('status').textContent=(opts.method||'GET')+' '+path;$('responseMeta').textContent=admin?'Admin':'Public';try{const r=await fetch(path,{...opts,headers});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body=text}$('status').textContent=r.status+' '+r.statusText;$('result').textContent=typeof body==='string'?body:JSON.stringify(body,null,2);if(admin){$('authNotice').className='notice '+(r.ok?'ok':'');$('authNotice').textContent=r.status===503?'Admin API is not configured on the server. Set ADMIN_API_KEY in Render Environment, then redeploy.':r.status===401?'Admin key rejected. Make sure this value exactly matches Render ADMIN_API_KEY.':r.ok?'Admin authentication accepted.':'Admin request returned '+r.status+'.'}}catch(e){$('status').textContent='Request failed';$('result').textContent=String(e);if(admin){$('authNotice').className='notice';$('authNotice').textContent='The browser could not reach the API.'}}}
function endpoint(title,path,admin=false,button='Run'){return '<div class="endpoint"><div class="endpoint-title"><span class="badge get">GET</span><strong>'+esc(title)+'</strong></div><code>'+esc(path)+'</code><div style="margin-top:8px"><button '+(admin?'':'class="blue"')+' data-action="'+esc(path)+'" data-admin="'+admin+'">'+button+'</button></div></div>'}
$('publicEndpoints').innerHTML=endpoint('Health check','/health')+endpoint('Dataset statistics','/stats')+endpoint('Categories','/categories')+endpoint('Provinces','/provinces')+endpoint('Municipalities','/municipalities')+endpoint('Procurement types','/procurement-types')+'<div class="endpoint"><div class="endpoint-title"><span class="badge get">GET</span><strong>Tender search</strong></div><code>/tenders</code><div class="grid"><div class="field"><label for="q">Search</label><input id="q" placeholder="road, construction, cleaning..." /></div><div class="field"><label for="municipality">Municipality</label><input id="municipality" placeholder="ETHEKWINI" /></div><div class="field"><label for="procurementType">Procurement type</label><select id="procurementType"><option value="">Any type</option><option>TENDER</option><option>RFQ</option><option>QUOTATION</option><option>EOI</option><option>ADDENDUM</option><option>AWARD</option><option>CANCELLATION</option><option>NOTICE</option></select></div><div class="field"><label for="limit">Results</label><input id="limit" type="number" min="1" max="100" value="20" /></div></div><button class="blue" id="searchButton">Search tenders</button></div><div class="endpoint"><div class="endpoint-title"><span class="badge get">GET</span><strong>Tender by ID</strong></div><code>/tenders/{id}</code><div class="field"><label for="tenderId">Tender ID</label><input id="tenderId" placeholder="Database tender ID" /></div><button class="blue" id="tenderButton">Run</button></div>';
$('adminEndpoints').innerHTML=endpoint('Admin dashboard','/admin/dashboard',true)+endpoint('Municipality adapters','/admin/municipalities',true)+'<div class="endpoint"><div class="endpoint-title"><span class="badge post">POST</span><strong>Run municipality ingestion</strong></div><code>/admin/municipalities/{code}/ingest</code><div class="grid"><div class="field"><label for="ingestCode">Municipality code</label><input id="ingestCode" value="ETHEKWINI" /></div><div class="field"><label for="backfill">Backfill</label><select id="backfill"><option value="false">false</option><option value="true">true</option></select></div></div><button class="green" id="ingestButton">Run ingestion</button></div><div class="endpoint"><div class="endpoint-title"><span class="badge post">POST</span><strong>Relink existing tenders</strong></div><code>/admin/municipalities/{code}/relink</code><div class="grid"><div class="field"><label for="relinkCode">Municipality code</label><input id="relinkCode" value="ETHEKWINI" /></div><div class="field"><label for="relinkSource">Source</label><input id="relinkSource" value="ETHEKWINI" /></div></div><button class="green" id="relinkButton">Relink tenders</button></div><div class="endpoint"><div class="endpoint-title"><span class="badge post">POST</span><strong>Manual tender ingestion</strong></div><code>/admin/tenders</code><div class="field"><label for="manualJson">JSON payload</label><textarea id="manualJson">{\n  "source":"MANUAL",\n  "sourceUrl":"https://example.gov.za/tender",\n  "ocid":"manual:example:001",\n  "releaseId":"manual-release-001",\n  "tenderNumber":"RFQ-001",\n  "procurementType":"RFQ",\n  "municipalityCode":"ETHEKWINI",\n  "title":"Example municipal RFQ",\n  "organisation":"eThekwini Municipality",\n  "category":"CONSTRUCTION",\n  "province":"KwaZulu-Natal",\n  "location":"Durban",\n  "isOpportunity":true\n}</textarea></div><button class="green" id="manualButton">Save tender</button></div>';
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>call(b.dataset.action,{},b.dataset.admin==='true')));
$('searchButton').addEventListener('click',()=>{const p=new URLSearchParams({page:'1',limit:$('limit').value||'20'});if($('q').value)p.set('q',$('q').value);if($('municipality').value)p.set('municipality',$('municipality').value);if($('procurementType').value)p.set('procurementType',$('procurementType').value);call('/tenders?'+p)});
$('tenderButton').addEventListener('click',()=>call('/tenders/'+encodeURIComponent($('tenderId').value)));
$('ingestButton').addEventListener('click',()=>{const c=$('ingestCode').value.trim();call('/admin/municipalities/'+encodeURIComponent(c)+'/ingest?backfill='+$('backfill').value,{method:'POST'},true)});
$('relinkButton').addEventListener('click',()=>{const c=$('relinkCode').value.trim();call('/admin/municipalities/'+encodeURIComponent(c)+'/relink',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:$('relinkSource').value.trim()})},true)});
$('manualButton').addEventListener('click',()=>{let body;try{body=JSON.parse($('manualJson').value)}catch(e){$('status').textContent='Invalid JSON';$('result').textContent=String(e);return}call('/admin/tenders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},true)});
</script></body></html>`;
